server:
  port: 9012

ribbon:
  ReadTimeout: 300000

# docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=d3M0@SGC.* -e MYSQL_DATABASE=demo -p 3306:3306 -d mysql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: d3M0@SGC.*
    hikari:
      maximumPoolSize: 10
      minimumIdle: 5
      poolName: oauth-jdbc-pool
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      INDENT_OUTPUT: true